removeStrategy:
  rbac: SYNC
  items: NONE
items:
  - kind: managedController
    name: good-boy
    configuration:
      kubernetes:
        memory: 3072
        fsGroup: "1000"
        cpus: 4.0
        readinessTimeoutSeconds: 5
        livenessInitialDelaySeconds: 300
        readinessInitialDelaySeconds: 30
        disk: 5
        readinessFailureThreshold: 100
        livenessTimeoutSeconds: 10
        # storageClassName: my-storage-class
        domain: good-boy
        # javaOptions: -XshowSettings:vm -XX:+AlwaysPreTouch -XX:+UseG1GC  -XX:+ParallelRefProcEnabled
        #   -XX:+UseStringDeduplication -Dhudson.slaves.NodeProvisioner.initialDelay=0
        # nodeSelectors: dedicated=sda-ci
        # yaml: |-
        #   ---
        # kind: StatefulSet
        # spec:
        #   template:
        #     metadata:
        #       annotations:
        #         cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        #     spec:
        #       tolerations:
        #       - key: "dedicated"
        #         operator: "Equal"
        #         value: "sda-ci"
        #         effect: "NoSchedule"
    properties:
    - configurationAsCode:
        bundle: "modern.good-boy"
  - kind: managedController
    name: fresh-boy
    configuration:
      kubernetes:
        memory: 3072
        fsGroup: "1000"
        cpus: 1.0
        readinessTimeoutSeconds: 5
        livenessInitialDelaySeconds: 300
        readinessInitialDelaySeconds: 30
        disk: 5
        readinessFailureThreshold: 100
        livenessTimeoutSeconds: 10
        domain: fresh-boy
  - kind: folder
    name: admin
    displayName: admin
    items:
    - kind: clusterOpProject
      name: restart-all-controllers
      concurrentBuild: true
      displayName: restart-all-controllers
      operations:
      - managedMasterClusterOperation:
          failureMode: IMMEDIATELY
          clusterOpSteps:
          - restartMasterNowClusterOpStep: {}
          timeoutSeconds: 0
          itemSource:
            jenkinsRootItemSource: {}
          inParallel: 0
          noRetries: 0
