apiVersion: "1"
id: "bad-boy"
description: "Casc Bundle following Best Practices"
version: "1"
jcasc:
  - "general.yaml"
  - "security.yaml"
plugins:
  - "plugins.yaml"
catalog:
  - "plugin-catalog.yaml"
items:
  - "items-jobs.yaml"
