apiVersion: v1
kind: "PersistentVolumeClaim"
metadata:
  name: "maven-cache"
  namespace: {{ .Values.agents.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
