OperationsCenter:
  JavaOpts: >-
    -XX:InitialRAMPercentage=50.0
    -XX:MaxRAMPercentage=50.0
  Resources:
    Limits:
      Memory: "4G"
      Cpu: 2
    Requests:
      Memory: "4G"
      Cpu: 2
  CasC:
    Enabled: true
  ConfigMapName: oc-casc-bundle
  ContainerEnv:
    - name: SECRETS
      value: /var/run/secrets/cjoc
  ExtraVolumes:
    - name: oc-secrets
      secret:
        secretName: oc-secrets
  ExtraVolumeMounts:
    - name: oc-secrets
      mountPath: /var/run/secrets/cjoc
      readOnly: true
  NodeSelector:
    ci_type: cb-apps
  Tolerations:
    - key: dedicated
      operator: Equal
      value: cb-apps
      effect: NoSchedule
  License:
    Evaluation:
      Enabled: true
      FirstName: ${LicFirstName}
      LastName: ${LicLastName}
      Email: ${LicEmail}
      Company: ${LicCompany}
Hibernation:
  Enabled: true
Master:
  JavaOpts: >-
    -XX:InitialRAMPercentage=50.0
    -XX:MaxRAMPercentage=50.0
Agents:
  SeparateNamespace:
    Enabled: true
    Name: ${agentNamespace}
