apiVersion: "1"
id: "jenkins"
version: "1"
jcasc:
  - main.yaml
  - location.yaml
  - credentials.yaml
  - controllerBundleStorageSCM.yaml
  - security.yaml
plugins:
  - plugins.yaml
items:
  - items-controllers.yaml
rbac:
  - rbac.yaml
